blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/specula-principum/speculum-principum/discussions
    about: Please use GitHub Discussions for general questions or ideas.
